-- AlterTable
ALTER TABLE "VisualTypes" ALTER COLUMN "visualType" SET DEFAULT 'PILL',
ALTER COLUMN "size" SET DEFAULT 'MEDIUM',
ALTER COLUMN "pattern" SET DEFAULT 'SOLID',
ALTER COLUMN "opacity" SET DATA TYPE DOUBLE PRECISION;
